# Generated by Django 5.0.3 on 2024-04-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('DueñoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=20)),
                ('CorreoElectronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('EmpleadoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('HorarioTrabajo', models.CharField(max_length=100)),
                ('CorreoElectronico', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosMedicamentos',
            fields=[
                ('ProductoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CantidadInventario', models.PositiveIntegerField()),
                ('Proveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('CitaID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('MotivoVisita', models.CharField(max_length=200)),
                ('Estado', models.CharField(max_length=100)),
                ('Observaciones', models.TextField()),
                ('EmpleadoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasReportes',
            fields=[
                ('EstadisticasReportesID', models.AutoField(primary_key=True, serialize=False)),
                ('CitasAtendidas', models.PositiveIntegerField()),
                ('TipoServiciosSolicitados', models.CharField(max_length=200)),
                ('IngresosGenerados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OtrosDatosEstadisticos', models.TextField()),
                ('CitaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.cita')),
            ],
        ),
        migrations.CreateModel(
            name='FacturacionPagos',
            fields=[
                ('FacturaID', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroFactura', models.CharField(max_length=100)),
                ('FechaEmision', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MetodoPago', models.CharField(max_length=100)),
                ('EstadoPago', models.CharField(max_length=100)),
                ('DetallePago', models.TextField()),
                ('CitaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('MascotaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Especie', models.CharField(max_length=100)),
                ('Raza', models.CharField(max_length=100)),
                ('Edad', models.PositiveIntegerField()),
                ('Seño', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('Color', models.CharField(max_length=100)),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('NotasAdicionales', models.TextField()),
                ('DueñoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.dueño')),
            ],
        ),
        migrations.CreateModel(
            name='FichaDesparacitacion',
            fields=[
                ('FichaDesparacitacionID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaDesparacitacion', models.DateField()),
                ('TipoDesparacitacion', models.CharField(max_length=100)),
                ('Dosis', models.CharField(max_length=100)),
                ('NotasAdicionales', models.TextField()),
                ('MascotaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='MascotaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascota'),
        ),
        migrations.CreateModel(
            name='FacturacionProductosMedicamentos',
            fields=[
                ('FacturacionProductosMedicamentosID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveIntegerField()),
                ('FacturaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.facturacionpagos')),
                ('ProductoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.productosmedicamentos')),
            ],
        ),
    ]
