# Generated by Django 5.0.3 on 2024-04-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dueño',
            unique_together={('Nombres', 'Apellidos', 'Direccion', 'Telefono', 'CorreoElectronico')},
        ),
    ]
