# Generated by Django 5.0.2 on 2024-04-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0002_alter_dueño_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cita',
            new_name='citas',
        ),
        migrations.RenameModel(
            old_name='Dueño',
            new_name='dueños',
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='empleados',
        ),
        migrations.RenameModel(
            old_name='Mascota',
            new_name='mascotas',
        ),
        migrations.AlterUniqueTogether(
            name='dueños',
            unique_together=set(),
        ),
    ]
