# Generated by Django 5.0.2 on 2024-04-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0003_rename_cita_citas_rename_dueño_dueños_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='Seño',
        ),
    ]
