# Generated by Django 5.0.2 on 2024-04-21 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0004_remove_mascotas_seño'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='Sexo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
