version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: django-api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
     - 5432:5432
    restart: always
    container_name: db-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    

volumes:
  db_data:
